### ISSUE TITLE
Adding new sites

### ISSUE THREAD

**Issue by thuijssoon** [ChrisWiegman/Primary-Vagrant#15]
Hi Chris,

Thanks so much for this project! Could you maybe give an example of adding a site to this vagrant install? I have done the following:

In the vagrant file:
1. Added an alias to `config.hostsupdater.aliases: "test.pv"`
2. Added a drive mapping: `config.vm.synced_folder "sites/test", "/var/www/test.pv", :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]`

In the vhosts.pp file:
1. Added `apache::vhost { 'test.pv':
    docroot                  => '/var/www/test.pv',
    directory                => '/var/www/test.pv',
    directory_allow_override => 'All',
    ssl                      => true,
    template                 => '/var/vagrant/conf/vhost.conf.erb',
}`

I created a folder named test in de sites folder and added an index.html file to the folder.

When I reloaded vagrant and provisioned it, I get the 'Apache2 Ubuntu Default Page' and not the index.html file I created.

Have a missed something?

Thanks for your help!

Thijs

**Comment by ChrisWiegman** [comment]
Are other hosts working for you?
