### ISSUE TITLE
Theme install directory

### ISSUE THREAD

**Issue by ltarasiewicz** [ChrisWiegman/Primary-Vagrant#21]
Hello,

I just wanted to ask why themes for wordpress.stable.pv  are installed outside the wordpress directory? New themes are installed in the parent directory 'wordpress/content/themes'. Obviously, the wordpress install at wordpress.sable.pv has access to it. Novertheless, this setup is a bit problematic.

Is there a way to change this behaviour?

Thank you!

**Comment by michaelbeil** [comment]
Gonna close this. Let us know if you have any more issues.
