### ISSUE TITLE
SSH Provisioner Issue

### ISSUE THREAD

**Issue by jakejackson1** [ChrisWiegman/Primary-Vagrant#27]
Hi,

This Vagrant box looks great but I've had some issues provisioning it. 

I get the following errors:

"The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir -p /tmp/vagrant-puppet-3

Stderr for the command:

sudo: parse error in /etc/sudoers near line 9
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin"

Any ideas how to fix it?

**Comment by michaelbeil** [comment]
what versions of vagrant and virtual box do you have?

**Comment by ptt-homme** [comment]
Hi,

I supposed you are using Windows,  aren't you? If so, I probably have a fix to solve your problem and maybe #23. 

A quick fix before proposing a PR tomorrow,  try to comment these lines in the init.pp files in manifest folder:
```
#file { 'sudoers':
#	path    => '/etc/sudoers',
#	ensure  => file,
#	mode => '440',
#	source => '/var/vagrant/conf/sudoers',
#}
```
Let us know, if the box provisioning fine!

**Comment by blueliquiddesigns** [comment]
I'm running the latest vagrant and virtual box. And yes I'm on Windows 7 64 Bit. 

I made the modification suggested but am still having issues (the hiera.yaml missing #23 is one of them).

My log indicated:

```
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> default: Notice: Compiled catalog for pv in environment production in 7.97 seconds
==> default: Error: Could not set 'link' on ensure: Protocol error - (/var/www/phpmyadmin.pv/config.inc.php, /var/www/phpmyadmin.pv/phpmyadmin/config.inc.php) at 269:/tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp
==> default: Error: Could not set 'link' on ensure: Protocol error - (/var/www/phpmyadmin.pv/config.inc.php, /var/www/phpmyadmin.pv/phpmyadmin/config.inc.php) at 269:/tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp
==> default: Wrapped exception:
==> default: Protocol error - (/var/www/phpmyadmin.pv/config.inc.php, /var/www/phpmyadmin.pv/phpmyadmin/config.inc.php)
==> default: Error: /Stage[main]/Main/File[/var/www/phpmyadmin.pv/phpmyadmin/config.inc.php]/ensure: change from absent to link failed: Could not set 'link' on ensure: Protocol error - (/var/www/phpmyadmin.pv/config.inc.php, /var/www/phpmyadmin.pv/phpmyadmin/config.inc.php) at 269:/tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: executed successfully
==> default: Notice: /Stage[main]/Composer/Exec[composer-update]/returns: executed successfully
==> default: Notice: /Stage[main]/Mailcatcher::Service/Service[mailcatcher]/ensure: ensure changed 'stopped' to 'running'
==> default: Notice: Finished catalog run in 26.82 seconds
SSH command responded with a non-zero exit status. Vagrant assumes this means the command failed.
```

**Comment by timmaybrown** [comment]
I have the same issue. Any update on this or further things to try?

**Comment by ptt-homme** [comment]
Hi @timmaybrown,

Which one? Could you be a bit more explicit ;-)

**Comment by timmaybrown** [comment]
the invalid sudoers file, but I also saw warning about  the issue:
`Config file /etc/puppet/hiera.yaml not found`

Destroyed and retrying to to make sure init.pp ignores the sudoers file (i think i forgot to save). However I realized I have Vagrant 1.6.5 so after this "vagrant up" completes If the issue persists I'll be sure to upgrade that and see if that helps.

When looking at the `sudoers` and `sudoers.d/*` files as root using visudo I couldn't see any syntax errors, but I must have been mis-reading the sudoer's syntax documentation, because it definitely was complaining about a syntax error on line 9, but wasn't able to see any invalid syntax as my sudoers file matched many examples I found on the web.

**Comment by timmaybrown** [comment]
I now get the error shown below when immediately SSH into the vagrant box. Any thoughts would be much appreciated. I still get the missing hiera.yaml warning when re-provisioning.
```
/home/vagrant/.zshrc:3: command not found: ^M
/home/vagrant/.zshrc:9: command not found: ^M
/home/vagrant/.zshrc:12: command not found: ^M
/home/vagrant/.zshrc:15: command not found: ^M
/home/vagrant/.zshrc:18: command not found: ^M
/home/vagrant/.zshrc:21: command not found: ^M
/home/vagrant/.zshrc:24: command not found: ^M
/home/vagrant/.zshrc:27: command not found: ^M
/home/vagrant/.zshrc:30: command not found: ^M
/home/vagrant/.zshrc:35: command not found: ^M
/home/vagrant/.zshrc:40: command not found: ^M
/home/vagrant/.zshrc:43: command not found: ^M
/home/vagrant/.zshrc:48: command not found: ^M
/home/vagrant/.zshrc:49: command not found: ^M
/home/vagrant/.zshrc:51: command not found: ^M
/home/vagrant/.zshrc:54: command not found: ^M
/home/vagrant/.zshrc:source:55: no such file or directory: /home/vagrant/.oh-my-
zsh^M/oh-my-zsh.sh^M
/home/vagrant/.zshrc:56: command not found: ^M
/home/vagrant/.zshrc:59: command not found: ^M
/home/vagrant/.zshrc:66: command not found: ^M
/home/vagrant/.zshrc:69: command not found: ^M
/home/vagrant/.zshrc:72: command not found: ^M
```

**Comment by ptt-homme** [comment]
The easiest way to get it works temporarily is to comment in init.pp lines which refer to sudoers:
```
#file { 'sudoers':
#   path    => '/etc/sudoers',
#   ensure  => file,
#   mode => '440',
#   source => '/var/vagrant/conf/sudoers',
#}
```

**Comment by timmaybrown** [comment]
Commenting it out got past that issue but now I get the issue I posted previously.

Thanks!
-tim

**Comment by ptt-homme** [comment]
> When looking at the sudoers and sudoers.d/* files as root using visudo I couldn't see any syntax errors, but I must have been mis-reading the sudoer's syntax documentation, because it definitely was complaining about a syntax error on line 9, but wasn't able to see any invalid syntax as my sudoers file matched many examples I found on the web.

There is no syntax errors, in fact as you probably use Windows end-of-line in your git settings, normal linux eol are replaced making this error happens.

> Commenting it out got past that issue but now I get the issue I posted previously.

??

**Comment by timmaybrown** [comment]
I had posted this but deleted it and re-posting now:

I now get the error shown below when immediately SSH into the vagrant box. Any thoughts would be much appreciated. I still get the missing hiera.yaml warning when re-provisioning.
````
/home/vagrant/.zshrc:3: command not found: ^M
/home/vagrant/.zshrc:9: command not found: ^M
/home/vagrant/.zshrc:12: command not found: ^M
/home/vagrant/.zshrc:15: command not found: ^M
/home/vagrant/.zshrc:18: command not found: ^M
/home/vagrant/.zshrc:21: command not found: ^M
/home/vagrant/.zshrc:24: command not found: ^M
/home/vagrant/.zshrc:27: command not found: ^M
/home/vagrant/.zshrc:30: command not found: ^M
/home/vagrant/.zshrc:35: command not found: ^M
/home/vagrant/.zshrc:40: command not found: ^M
/home/vagrant/.zshrc:43: command not found: ^M
/home/vagrant/.zshrc:48: command not found: ^M
/home/vagrant/.zshrc:49: command not found: ^M
/home/vagrant/.zshrc:51: command not found: ^M
/home/vagrant/.zshrc:54: command not found: ^M
/home/vagrant/.zshrc:source:55: no such file or directory: /home/vagrant/.oh-my-
zsh^M/oh-my-zsh.sh^M
/home/vagrant/.zshrc:56: command not found: ^M
/home/vagrant/.zshrc:59: command not found: ^M
/home/vagrant/.zshrc:66: command not found: ^M
/home/vagrant/.zshrc:69: command not found: ^M
/home/vagrant/.zshrc:72: command not found: ^M
````

**Comment by ptt-homme** [comment]
clone [this repo](https://github.com/ptt-homme/Primary-Vagrant/tree/fix_sudoers), it should work properly till it is merged into master!

**Comment by timmaybrown** [comment]
K thanks. So this might be a newbie question/not the place to ask such a question, but what is the best practice to keep my primary vagrant repo in sync with this project whilst maintaining my adjustments to the Vagrantfile and vhosts.pp, etc.? 

It warned about merge conflicts when I fetched changes with the upstream/master so I am just curious if there is a resource/tutorial that explains the best practice to keeping my repo up to date when commits like yours are available. Thanks for your help thus far!

**Comment by ptt-homme** [comment]
Your VM is up?

I would do something like this:
* git stash
* git pull
* git submodule update --recursive
* git stash pop

Hope this help!

Ptt-homme

**Comment by timmaybrown** [comment]
Yeah my can is up it just warns about not knowing what ^M is in my previous comment. I'm doing a fresh clone of your repo and will see if that fixes it.

Thanks for the commands. I think that makes sense. Have a lot more to learn with git (used mercurial primarily)

thanks!
-tim

**Comment by michaelbeil** [comment]
@timmaybrown ~~> 
* https://help.github.com/articles/syncing-a-fork 
* https://www.atlassian.com/git/tutorials/syncing/git-pull

using `git pull <remote> <branch>`  and `git mergetool` can be helpful for keeping your local PV in sync.

And Tower is a worthy Git client to consider: 
* http://www.git-tower.com 
* http://www.git-tower.com/blog/git-cheat-sheet-detail 


Master is updated @blueliquiddesigns @ptt-homme @timmaybrown.

**Comment by blueliquiddesigns** [comment]
Thanks Michael.

I removed the entire package and did a fresh clone to ensure everything was fully up to date but still had errors thrown during `vagrant up` and `vagrant provision`. I'm not sure if I need to worry about it as the website's appear to load when I access the links like `http://wordpress.core.pv`. 


Here's the condensed `vagrant up` errors.
```
==> default: Running provisioner: puppet...
==> default: Running Puppet with init.pp...
==> default: stdin: is not a tty
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> default: Notice: Compiled catalog for pv in environment production in 7.64 seconds
==> default: Error: Could not set 'link' on ensure: Protocol error - (/var/www/phpmyadmin.pv/config.inc.php, /var/www/phpmyadmin.pv/phpmyadmin/config.inc.php) at 269:/tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp
==> default: Error: Could not set 'link' on ensure: Protocol error - (/var/www/phpmyadmin.pv/config.inc.php, /var/www/phpmyadmin.pv/phpmyadmin/config.inc.php) at 269:/tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp
==> default: Wrapped exception:
==> default: Protocol error - (/var/www/phpmyadmin.pv/config.inc.php, /var/www/phpmyadmin.pv/phpmyadmin/config.inc.php)
==> default: Error: /Stage[main]/Main/File[/var/www/phpmyadmin.pv/phpmyadmin/config.inc.php]/ensure: change from absent to link failed: Could not set 'link' on ensure: Protocol error - (/var/www/phpmyadmin.pv/config.inc.php, /var/www/phpmyadmin.pv/phpmyadmin/config.inc.php) at 269:/tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: executed successfully
==> default: Notice: /Stage[main]/Composer/Exec[composer-update]/returns: executed successfully
==> default: Notice: /Stage[main]/Mailcatcher::Service/Service[mailcatcher]/ensure: ensure changed 'stopped' to 'running'
==> default: Notice: /Stage[main]/Mysql::Server::Service/Service[mysqld]/ensure: ensure changed 'stopped' to 'running'
==> default: Notice: /Stage[main]/Apache/Service[apache]/ensure: ensure changed 'stopped' to 'running'
==> default: Notice: Finished catalog run in 43.21 seconds
```

And the `vagrant provision` errors:

```
==> default: Running provisioner: puppet...
==> default: Running Puppet with init.pp...
==> default: stdin: is not a tty
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> default: Notice: Compiled catalog for pv in environment production in 7.65 seconds
==> default: Error: Could not set 'link' on ensure: Protocol error - (/var/www/phpmyadmin.pv/config.inc.php, /var/www/phpmyadmin.pv/phpmyadmin/config.inc.php) at 269:/tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp
==> default: Error: Could not set 'link' on ensure: Protocol error - (/var/www/phpmyadmin.pv/config.inc.php, /var/www/phpmyadmin.pv/phpmyadmin/config.inc.php) at 269:/tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp
==> default: Wrapped exception:
==> default: Protocol error - (/var/www/phpmyadmin.pv/config.inc.php, /var/www/phpmyadmin.pv/phpmyadmin/config.inc.php)
==> default: Error: /Stage[main]/Main/File[/var/www/phpmyadmin.pv/phpmyadmin/config.inc.php]/ensure: change from absent to link failed: Could not set 'link' on ensure: Protocol error - (/var/www/phpmyadmin.pv/config.inc.php, /var/www/phpmyadmin.pv/phpmyadmin/config.inc.php) at 269:/tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: executed successfully
==> default: Notice: /Stage[main]/Composer/Exec[composer-update]/returns: executed successfully
==> default: Notice: /Stage[main]/Mailcatcher::Service/Service[mailcatcher]/ensure: ensure changed 'stopped' to 'running'
==> default: Notice: Finished catalog run in 29.78 seconds
```

**Comment by michaelbeil** [comment]
@blueliquiddesigns what happens when you visit phpmyadmin.pv?

**Comment by blueliquiddesigns** [comment]
PHPMyAdmin works without any issues. The only problems I have had is accessing mailcatcher (the page 404s) and I haven't been able to correctly ssh tunnel into the box. Everything else appears to be working fine.

**Comment by michaelbeil** [comment]
@ChrisWiegman, any ideas on this?

**Comment by ChrisWiegman** [comment]
Looking at it. What I need to do is get a Windows box for testing this stuff (or get someone who has one on the repo itself)
