### ISSUE TITLE
SSL Privacy Error error

### ISSUE THREAD

**Issue by BurnzZ** [ChrisWiegman/Primary-Vagrant#30]
Hello!

Thanks for creating this awesome box BTW!

It works great. However I have this problem in my SSL when I access it on my host:

![screen shot 2015-03-17 at 2 00 44 am](https://cloud.githubusercontent.com/assets/3449761/6673016/0d81fb72-cc4b-11e4-8c7e-1ecce8733321.png)

I've read that:
> I've provided a top-level wildcard SSL certificate. No further SSL certificate should be needed.

So I haven't configured any SSL certs myself at this point.

Also, I've configured my **vhosts.pp** as:
```
apache::vhost { 'blog.pv' :
        docroot => '/var/www/blog.pv',
        directory => '/var/www/blog.pv',
        directory_allow_override => 'All',
        ssl => true,
        template => '/var/vagrant/conf/vhost.conf.erb',
}
```

Also added `blog.pv` to the **config.hostsupdater.aliases**.
As well as the appropriate `config.vm.synced_folder` settings

Have I missed any steps in these?
The WP blog I'm working on is a subdir in a server working under https. I really need to build it on working in https as well, so I can mimic the production site's behavior.

EDIT:

here's a result of the `curl -v -k https://blog.pv` inside the VM:

```
* Rebuilt URL to: https://blog.pv/
* Hostname was NOT found in DNS cache
*   Trying 192.168.13.101...
* Connected to blog.pv (192.168.13.101) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: C=US; ST=Hawaii; L=Makawao; O=Primary Vagrant; CN=*
* 	 start date: 2014-05-30 22:05:43 GMT
* 	 expire date: 2024-05-27 22:05:43 GMT
* 	 issuer: C=US; ST=Hawaii; L=Makawao; O=Primary Vagrant; CN=*
* 	 SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: blog.pv
> Accept: */*
>
< HTTP/1.1 302 Found
< Date: Mon, 16 Mar 2015 18:16:08 GMT
* Server Apache/2.4.7 (Ubuntu) is not blacklisted
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.6
< X-Pingback: https://blog.pv/xmlrpc.php
< X-UA-Compatible: IE=edge,chrome=1
< Location: https://blog.pv?password-protected=login&redirect_to=https%3A%2F%2Fblog.pv%2F
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
<
* Connection #0 to host blog.pv left intact
```

UPDATE:

I checked the error logs and found this line:
`[ssl:warn] [pid 4389] AH01909: RSA certificate configured for blog.pv:443 does NOT include an ID which matches the server name`

I'm currently on **OS X 10.10.2**

Cheers!

**Comment by BurnzZ** [comment]
please help! anyone?

**Comment by michaelbeil** [comment]
@ChrisWiegman any ideas?

**Comment by ChrisWiegman** [comment]
You'll need to bypass SSL Verification on your cURL call. The CURLOPT_SSL_VERIFYPEER option should do it but note that you do NOT want that in your production code. 

The reason for the error is the certificate used is not tied to any domain which isn't proper if SSL verification is turned on. The only other alternative for you would be to install a cert for the domain in question.
