### ISSUE TITLE
Apache module issues

### ISSUE THREAD

**Issue by mkuplens** [ChrisWiegman/Primary-Vagrant#31]
Looks like there's a problem with the linked Apache module–

Error on clone:
```
Submodule 'sites/wordpress/wptest' (git@github.com:manovotny/wptest.git) registered for path 'sites/wordpress/wptest'
Cloning into 'modules/apache'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:example42/puppet-apache.git' into submodule path 'modules/apache' failed
```

And error on `vagrant up` from downloaded zip:
```
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type apache::module at /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/custom/apache.pp:1 on node pv
==> default: Wrapped exception:
==> default: Invalid resource type apache::module
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type apache::module at /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/custom/apache.pp:1 on node pv
```

**Comment by michaelbeil** [comment]
This is on https://github.com/ChrisWiegman/Primary-Vagrant/releases/tag/1.2.1 ?

**Comment by mkuplens** [comment]
I'm afraid so. Running on an OS X machine, in case it makes a difference.

**Comment by michaelbeil** [comment]
Are you pulling down PV for the first time?

**Comment by mkuplens** [comment]
Yes

**Comment by michaelbeil** [comment]
And you have done the following?

Install Vagrant, VirtualBox, and the VirtualBox extensions for your environment.

Once Vagrant is installed you'll want two plugins to update your local hosts file and update the VirtualBox Guest additions in the Ubuntu install.

`vagrant plugin install vagrant-vbguest`

`vagrant plugin install vagrant-hostsupdater` 

Download or clone this repo onto your local machine:

`$ git clone --recursive git@github.com:ChrisWiegman/Primary-Vagrant.git`

Run `vagrant up` from the folder where you're storing this repository

**Comment by mkuplens** [comment]
Haven't been able to clone (issue with the apache repo), been trying with the .zip package

**Comment by michaelbeil** [comment]
K.

**Comment by mkuplens** [comment]
K–fixed the clone issue w/ SSH key reconfig; zipfile didn't seem to include the correct components, nor does clone from Github's provided URL (sidebar).

Currently re-downloading via clone will update once that's completed.

**Comment by michaelbeil** [comment]
:+1:

**Comment by michaelbeil** [comment]
another idea is to use a GUI like the GitHub client or Tower.

**Comment by mkuplens** [comment]
:+1:  That re-clone worked. Odd that the other ways of fetching cause failure!

**Comment by michaelbeil** [comment]
How did you go about? 

`git clone --recursive git@github.com:ChrisWiegman/Primary-Vagrant.git` ??

**Comment by mkuplens** [comment]
Yes - once my public SSH was setup in my account it was able to retrieve the Apache module.

**Comment by michaelbeil** [comment]
Great!

**Comment by ChrisWiegman** [comment]
I need to look at the .zip. Never tried it to be honest, my understanding is that it would include submodules but apparently I may be wrong.
