### ISSUE TITLE
Documentation on usage

### ISSUE THREAD

**Issue by thomasdebruin** [ChrisWiegman/Primary-Vagrant#32]
Vagrant, Puppet and wp cli are all new to me.
Just want to use this to quickly spin up new WP websites in a lamp stack instead of wamp.
Just wondering if I follow the right steps for creating a new website:
- add alias in vagrantfile
- add synced_folder in vagrantfile
- vagrant reload
- add db in mysql.pp
- login over ssh

wp cli (http://wp-cli.org)
- run wp core download
- run wp core config
- run wp core install

It works, but I'm not sure if this is the way to go?

Something like https://github.com/aliso/vvv-site-wizard/blob/master/vvv would speed up this process, but it's probably not compatible with pv

**Comment by michaelbeil** [comment]
Utilizing something like site wizard would be great to integrate. For now that is the best method, unfortunately. 

@ChrisWiegman, got any ideas to implement vvv site wizard?

**Comment by thomasdebruin** [comment]
There is also some overlap with yeoman (https://github.com/wesleytodd/YeoPress), but vvv is probably the way to go. Currently integrating vvv is beyond my skills, first I'll need to get used to basics of vagrant/puppet, do a couple of projects with it.

**Comment by schilke** [comment]
I feel a bit lost there, too - I'm either not sure if I'm missing something - or just don't get the full concept yet.
For example, if I'm planning to work on two WordPress projects (Mainly theme development, but plugins as well): Do I still have to set up a complete WordPress installation for each of them (so that I have 10 in the end of the day if I'm working on 10 projects simultanously)? That's probably a silly question if you're working on Linux (and do some symlink magic) - but I don't - and I strongly believe that I need some pointer here what I'm missing (if so).

**Comment by ChrisWiegman** [comment]
gerroald@ithemes.com <mailto:gerroald@ithemes.com> (that would help, eh?)


Chris Wiegman
Tel: (808) 250-3287 <tel:(512)%20428-8783>
https://www.chriswiegman.com  <https://www.chriswiegman.com/>
 <http://www.facebook.com/chris.wiegman>	 <http://www.facebook.com/chris.wiegman>	 <http://www.facebook.com/chris.wiegman>	 <http://www.facebook.com/chris.wiegman>	 <https://github.com/chriswiegman>

**Comment by thomasdebruin** [comment]
In my case I have a separate install per project, each project reflects a live website, so has many differences (version, plugins etc) per project. In my case a single codebase for all the projects would not work. Primary Vagrant main advantage for me is that you can quickly spin up a new wp website, install plugins (wp cli) etc. see above procedure.

What symlink magic do you expect? I might be missing it as well....
Probably you can develop a single theme or plugin an share the same code for different local projects by symlinking the folder, is this what you want to achieve?

**Comment by schilke** [comment]
Besides streamlining and automating more things (currently I'm using https://github.com/subash/prepros and an online staging server) the most interesting improvement would be to get the WordPress core stuff out of sight (I.e. killing the redundancy - I always develop on the latest stable version and try to keep client sites up to date).

From what I undestand this should be able with the synced_folder functionality - correct? But I'm still failing to figure out how.
Furthermore I know that sites/wordpress/content is there for a reason (I thought that's where the theme and/or mu-/plugins I'm working on should go?). 

I'm mostly missing a few real world examples - that would probably be the biggest help - at least for me as I'm more a creative person with a passion for code - not a true geek :grimacing:
