### ISSUE TITLE
Replace vagrant-hostsupdater

### ISSUE THREAD

**Issue by michaelbeil** [ChrisWiegman/Primary-Vagrant#34]
Seeing that vagrant-hostsupdater plugin is going out of style right about now, maybe we should go with the Vagrant Ghost plugin, developed by 10up?

Props for the heads up @zamoose: https://github.com/wpengine/hgv/issues/120

**Comment by ChrisWiegman** [comment]
already done in dev

**Comment by michaelbeil** [comment]
:+1:
