### ISSUE TITLE
Improve windows performance

### ISSUE THREAD

**Issue by thomasdebruin** [ChrisWiegman/Primary-Vagrant#36]
As a newbie i might be looking in the wrong direction. Performance on windows (windows 8.1 corei7 16gb ram SSD) was bad, the following made it less worse:
- increase memory (4096), cpus (4) and cpuexecutioncap (50%) in vagrantfile
- increase php memory to 2048

These settings are probably a bit of an overkill, a simple wp page still takes about 2 seconds to load.

My guess is that I need to modify the mysql settings, but I have no clue how to do this through puppet (I spend some hours on the internet). any thoughts?

Besides this, it could be the synced folders on windows, I had no luck to get fsd (https://github.com/GM-Alex/vagrant-winnfsd) working, neither smb (https://docs.vagrantup.com/v2/synced-folders/smb.html). any tips/thoughts?

**Comment by michaelbeil** [comment]
I'm not sure @thomasdebruin. You definitely shouldn't need such heightened settings. Would you check out our dev branch? https://github.com/ChrisWiegman/Primary-Vagrant/tree/dev

**Comment by thomasdebruin** [comment]
Thnx! I gave it a try:

First I had to rename the VM name in the vagrant file,
to avoid conflict with my current machine:
	v.customize ["modifyvm", :id, "--name", "Primary Vagrant2"]

Second: the dev version gives me 'could not find declared class apt',
I modified some code from the none dev version:

class { 'apt':
	always_apt_update => true }

Class['::apt::update'] -> Package <|
	title != 'python-software-properties'
	and title != 'software-properties-common'
|>

But it still gives me the  'could not find declared class apt' error,
Any tips how to get this working?

**Comment by thomasdebruin** [comment]
No succes on getting the dev branche up and running, after some hours or what I decided to give VVV a try. It works great, great performance. And vv is even greater (https://github.com/bradp/vv)

I don't mind using nginx locally and apache in the live environment, I just use it to develop a theme which I distribute with git. So in my case this seems the way to go.

**Comment by michaelbeil** [comment]
VVV with VV is a great Vagrant setup.
