### ISSUE TITLE
Issue with Puppet?

### ISSUE THREAD

**Issue by joelworsham** [ChrisWiegman/Primary-Vagrant#37]
I cloned in the files into a directory, navigated to it, and ran `vagrant up`.

I get this:
```
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

puppet provisioner:
* The following settings shouldn't exist: run
```

**Comment by michaelbeil** [comment]
Hey @joelworsham, can you tell me more about your environment?

Versions of Vagrant, VirtualBox, local machine OS, etc.

**Comment by michaelbeil** [comment]
Gonna close this out as we have not heard back.
