### ISSUE TITLE
Error when cloning submodules

### ISSUE THREAD

**Issue by raphaklr** [ChrisWiegman/Primary-Vagrant#38]
When running `git clone --recursive https://github.com/ChrisWiegman/Primary-Vagrant.git`, I get
```
Cloning into 'modules/apache'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:example42/puppet-apache.git' into submodule path 'modules/apache' failed
```

Why is that? [This](http://stackoverflow.com/questions/8197089/fatal-error-when-updating-submodule-using-git) stackoverflow answer says, that the URLs have to be changed to the public versions. Interestingly enough, other submodules seem to work...

**Comment by raphaklr** [comment]
Problem is solved. Something was wrong with my SSH key and I had to create a new one.

**Comment by michaelbeil** [comment]
Good to hear you got this squared away.
