### ISSUE TITLE
Fail on Vagrant Up: /etc/puppet/hiera.yaml not found

### ISSUE THREAD

**Issue by AvalonMel** [ChrisWiegman/Primary-Vagrant#40]
I'm running:
- Mac OSX
- Virtual Box 4.3.28
- Vagrant 1.7.2
- I cloned the repo using `git clone --recursive git@github.com:ChrisWiegman/Primary-Vagrant.git Primary-Vagrant`
- I changed the folder name from 'Primary Vagrant' to 'pv'
- I installed the two plugins

When I try to vagrant up I get the following error:
```
default: Running provisioner: puppet...
==> default: Running Puppet with init.pp...
==> default: stdin: is not a tty
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class postfix at /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp:217 on node pv
==> default: Wrapped exception:
==> default: Could not find declared class postfix
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class postfix at /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp:217 on node pv
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
I'm new to Vagrant, etc so I'm not sure what to be looking for to fix this. Can anyone lend a hand?

When I try to access any of the pre-configured sites I just an ERR_CONNECTION_REFUSED error in Chrome.

**Comment by michaelbeil** [comment]
Did you happen to have any other Virtual Boxes running?

**Comment by AvalonMel** [comment]
I have some installed but they're all powered off.

**Comment by arnlen** [comment]
It think it's because of Postfix:

```
ArgumentError: Could not find declared class postfix
```

Did you have this error while cloning repo?

```
Submodule path 'sites/wordpress/wptest': checked out '366d02b72a674535ee459e5ee2532016c35c50a9'
Unable to checkout '39146cab2fd84d919e6dc7d79ad6d71f8bb30bf5' in submodule path 'modules/postfix'
```

I've just created this related issue: https://github.com/ChrisWiegman/Primary-Vagrant/issues/41

**Comment by ChrisWiegman** [comment]
This has been fixed in 'dev.' I will not be back porting the fix to the current master branch as dev includes a major update that will be released soon.
