### ISSUE TITLE
Git clone: Error with submodule Postfix

### ISSUE THREAD

**Issue by arnlen** [ChrisWiegman/Primary-Vagrant#41]
When cloning the repos, all submodules seem to be installed successfully, but Postfix wasn't:

```
$ git clone --recursive git@github.com:ChrisWiegman/Primary-Vagrant.git
Cloning into 'Primary-Vagrant'...
remote: Counting objects: 2315, done.
remote: Total 2315 (delta 0), reused 0 (delta 0), pack-reused 2315
Receiving objects: 100% (2315/2315), 39.01 MiB | 8.54 MiB/s, done.
Resolving deltas: 100% (1007/1007), done.
Checking connectivity... done.

[...]

Submodule path 'sites/wordpress/wptest': checked out '366d02b72a674535ee459e5ee2532016c35c50a9'
Unable to checkout '39146cab2fd84d919e6dc7d79ad6d71f8bb30bf5' in submodule path 'modules/postfix'
```

Any one has this problem?

**Comment by chrisdhanaraj** [comment]
Yeah, same issue - I just manually cloned the repo Postfix was pointing to get around it, but it's not a permanent/real fix.

**Comment by ChrisWiegman** [comment]
Try the 'dev' branch. I have been working on it for a few months now and it is close to being Primary Vagrant 2.0 (note you might want to try it by cloning it fresh first as it changes a LOT)

**Comment by michaelbeil** [comment]
#42 fixes this for master.
