### ISSUE TITLE
Somehow misleading README.md

### ISSUE THREAD

**Issue by zu** [ChrisWiegman/Primary-Vagrant#44]
Below the headline "Configure your Apache VirtualHosts" it states:
Edit the file Vagrantfile and add paths to your own websites as well as a host entry to reach it.
When I look at the Vagrantfile I don't get where to add the path and host entry. Could be at line 18 	config.vm.hostname = "pv" but then do i have to add another line?

Also the manifests/vhosts.pp deosnt seem to exists but only an init.pp in the folder manifests.

But there is a pv-hosts file in the www/default folder that seems to hold the hosts.

Can/should I add here or is this file written automagically and I'd damage something?

I really want to learn it but I'm a bit confused.

Since you wrote "ask me if you have any questions", I'm asking although I'm not sure if this is the right place to do so.

Also what are the steps to manually add an existing web-folder structure to make it usable within Primary Vagrant. That should be about it, I guess:
1) adding the folder
2) creating and configuring the database
3) adding the virtual host

Is that correct. Otherwise please help me to understand by pointing me to documentation or other resources.

Thank you very much.

**Comment by iequalszero** [comment]
I am also having trouble getting this running now.

Been using PV for a few months now with no issues. As of last week, I'm getting dependency errors when doing a reload or up.

Tried starting over from scratch and noticed a few changes, one being HostUpdate is no longer being used. Instead it's using Ghost. This is the same area of the Vagrant file that I would update when adding new hosts.

Any help is appreciated.

**Comment by ChrisWiegman** [comment]
Hey y'all. I'm afraid the 2.0 (dev branch) version was way behind on documentation. I've fixed that today. Please take a look and let me know if that solves it for you.

Also note that, I've made the dev the default branch. @iequalszero, You might need to check to make sure you're still using the branch you were on.
