### ISSUE TITLE
vagrant up/provision error

### ISSUE THREAD

**Issue by ptasker** [ChrisWiegman/Primary-Vagrant#46]
Hi there,

I'm getting the following error when I try and run vagrant up for the first time, or run vagrant provision. Any ideas?

```
==> default: Running provisioner: puppet...
==> default: Running Puppet with init.pp...
==> default: stdin: is not a tty
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class apt at /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp:6 on node pv
==> default: Wrapped exception:
==> default: Could not find declared class apt
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class apt at /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/init.pp:6 on node pv
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by bobbravo2** [comment]
Make sure you run `git clone --recursive` — I was running into a similar issue without recursing all of the dependencies

**Comment by ChrisWiegman** [comment]
@bobbravo2 Would it help if I was to emphasize that in the docs? This seems like the most common problem folks run into.

**Comment by bobbravo2** [comment]
@chriswiegman yep. That's definitely a good way to proceed. Is there a pre-init script you can run as a "sanity check" before it breaks? Do a quick file_exists check?

**Comment by bobbravo2** [comment]
Also - you may want to update the blog post "VMs the holy grail of web development" with the note about --recursive, as that was my intro to the github repo (and I hastily 'git cloned' without reading the docs)

**Comment by eduwass** [comment]
God dammit the git clone step gets me every time!

IMO the **--recursive** option and this note:

> Note: you will need to have your public RSA key on file with GitHub to use this either way.

Should be in bold 42px Impact font in red surrounded by dancing baby gifs.
:grin:

**Comment by michaelbeil** [comment]
Fixed in https://github.com/ChrisWiegman/Primary-Vagrant/commit/55a2ee135f7d8b32c2ab213f15c7b9add51b3f0d, https://github.com/ChrisWiegman/Primary-Vagrant/commit/44330df813331f805030a6576ae7c3931e3b3430, and https://github.com/ChrisWiegman/Primary-Vagrant/commit/277af5b0cf8fc7c5eca359958e4e6e8e70455bca.
