### ISSUE TITLE
Box sometimes does not have enough memory for XDebug stack trace

### ISSUE THREAD

**Issue by yamitenshi** [ChrisWiegman/Primary-Vagrant#52]
See https://github.com/bolt/bolt/issues/4428

Sometimes, XDebug stack traces can become so large that they fill up all remaining memory and cause Apache to segfault.

If necessary, I'd be willing to upload the core dump I used to debug the issue somewhere, but it's a ~660MB file and my upload speed isn't great, so it might be faster to just follow the required steps to reproduce. When doing this, keep in mind that a `CoreDumpDirectory` must be set to a directory Apache can write to in Apache's config, and `ulimit -c unlimited` must be run to allow a core dump to be generated at all. To easily find the PID to attach `strace` to, run `pidof apache2` before and after a segfault. You'll see a number of PIDs, and the rightmost few will remain unchanged. The one immediately to the left of that will be the next to handle an incoming request, and will therefore be the one that segfaults when you refresh. So for instance, if the output before the segfault is

    620 615 614 612 585 580

And after the segfault it's

    623 620 615 614 585 580

You'd attach `strace` to PID 614.

**Comment by ChrisWiegman** [comment]
On large projects I have to bump the memory myself. You can do so easily in Vagrantfile. I'm hesitant to change the default however as it seems to be working for most and I don't want to put any more load on a user's computer that might not exactly be top of the line.
