### ISSUE TITLE
getimagesize(): SSL operation failed

### ISSUE THREAD

**Issue by timo002** [ChrisWiegman/Primary-Vagrant#53]
I'm trying to make use of `getimageszie()`, but I'm getting an OpenSSL error. How will I be able to fix this?

```
Warning:  getimagesize(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /var/www/www.gsmpunt.dev/pages/product.page.php on line 376
Warning:  getimagesize(): Failed to enable crypto in
```

I read something about the openssl certificate locations. So I checked it, see below

```
$ php -r "print_r(openssl_get_cert_locations());"
Array
(
    [default_cert_file] => /usr/lib/ssl/cert.pem
    [default_cert_file_env] => SSL_CERT_FILE
    [default_cert_dir] => /usr/lib/ssl/certs
    [default_cert_dir_env] => SSL_CERT_DIR
    [default_private_dir] => /usr/lib/ssl/private
    [default_default_cert_area] => /usr/lib/ssl
    [ini_cafile] => 
    [ini_capath] => 
)
```

The `default_cert_file` does not exist, so I downloaded this one http://curl.haxx.se/ca/cacert.pem into the `usr/lib/ssl/` folder and renamed it `cert.pem`. But no success either. What can I else do / try?

**Comment by ChrisWiegman** [comment]
I think I'm a bit confused here. Where are you making the getimagesize call? Apache should have no problem with https, it is using its own cert in /etc/apache2/ssl.

**Comment by timo002** [comment]
I created a new website (not WordPress) and there I have a script that uses `getimagesize()`. The image URL is over `https`. When I make it http instead of https, there is no issue.
