### ISSUE TITLE
Error cloning submodule for wordpress core (fatal: repository 'http://develop.git.wordpress.org/' not found)

### ISSUE THREAD

**Issue by crazyjaco** [ChrisWiegman/Primary-Vagrant#54]
I keep getting the following error when cloning the repo with --recursive:
```
Cloning into 'www/default/wordpress/core'...
fatal: repository 'http://develop.git.wordpress.org/' not found
Clone of 'git://develop.git.wordpress.org/' into submodule path 'www/default/wordpress/core' failed
```

I tried running git submodule update and received:
```
$ git submodule update
Cloning into 'www/default/wordpress/core'...
fatal: repository 'http://develop.git.wordpress.org/' not found
Clone of 'git://develop.git.wordpress.org/' into submodule path 'www/default/wordpress/core' failed
```

I had issues with the git clone and had to restart it a couple times because it kept losing the connection when trying to reach different submodules. I finally got all the way to this point and repeatedly hit this error with no variance.

Not sure if this is a local issue or something larger affecting the project.

**Comment by ChrisWiegman** [comment]
Thanks for the report. I wonder if WP has changed something. I'll try to take a look at this over the weekend

**Comment by michaelbeil** [comment]
What about using https://github.com/WordPress/WordPress.git instead?

**Comment by ChrisWiegman** [comment]
Im wondering if something is weird with your setup? I've checked out and successfully cloned fresh copies each day since I last posted here.

**Comment by crazyjaco** [comment]
It is entirely possible. I'll do some more testing. Thanks for taking a look!

**Comment by crazyjaco** [comment]
Tried refreshing my fork with your latest commits. Went fine until I went to do the submodule update.
Pretty much the same error:
```
$ git submodule update --recursive
Submodule path '../../../modules/mysql': checked out 'f06cc1269c0da682292d46e275d6da6442e73556'
Submodule path '../../../modules/stdlib': checked out '88a9a314c3e9cccbea5add95081655f2c14ec4c1'
Cloning into 'www/default/wordpress/core'...
fatal: repository 'http://develop.git.wordpress.org/' not found
Clone of 'git://develop.git.wordpress.org/' into submodule path 'www/default/wordpress/core' failed
```

A second attempt yielded:
```
$ git submodule update --recursive
Cloning into 'www/default/wordpress/core'...
fatal: repository 'http://develop.git.wordpress.org/' not found
Clone of 'git://develop.git.wordpress.org/' into submodule path 'www/default/wordpress/core' failed
```

A third:
```
$ git submodule update --recursive
Cloning into 'www/default/wordpress/core'...
fatal: unable to access 'http://develop.git.wordpress.org/': Failed connect to develop.git.wordpress.org:80; No error
Clone of 'git://develop.git.wordpress.org/' into submodule path 'www/default/wordpress/core' failed
```

Slightly different errors, but primarily the same. I cannot navigate to http://develop.git.wordpress.org in a regular web browser either. Not sure if I'm even supposed to be able to do that.

**Comment by crazyjaco** [comment]
After upgrading to PV v3 ( and getting a new router ) this no longer appears to be an issue.

Closing out request.

Thank you.
