### ISSUE TITLE
Mailcatcher link in default dashboard not working

### ISSUE THREAD

**Issue by crazyjaco** [ChrisWiegman/Primary-Vagrant#56]
I'm developing a [custom dashboard](https://github.com/crazyjaco/PV-Dashboard) and wanted to make sure all existing links on the default dashboard were carried over. I noticed that the Mailcatcher link doesn't seem to work, though.
Not sure if any configuration is needed for Mailcatcher.

http://mailcatcher.pv:1080/

**Comment by michaelbeil** [comment]
Does it results in a 404? Have you setup a mail catcher to send the email to a local smtp URL? http://mailcatcher.me/

**Comment by ChrisWiegman** [comment]
Also, check in your hosts file to verify the domain has been mapped.

**Comment by crazyjaco** [comment]
Finally had a chance to loop back to this.

Looks like my hosts file is good.

I took a look through the documentation. I see mailcatcher is in the init.pp.
According to the docs I need to add a line to the php.ini file to set apache's default smtp server to mailcatcher. Something like:
"sendmail_path = /usr/bin/env catchmail -f some@from.address"

Then run the command 'mailcatcher' while ssh'd into the vm.

I added the following line to the augeas block in the init.pp (just to test)
	'php-mailcatcher':
		entry   => 'mail function/sendmail_path',
		value   => '/usr/bin/env catchmail -f user@pv.pv',
		require => Class['php'];

Then I ran the mailcatcher command via ssh.

![mailcatcher_install](https://cloud.githubusercontent.com/assets/1782799/11915020/962e104a-a662-11e5-87b0-47d501326c2a.PNG)

When I navigate to http://mailcatcher.pv:1080, I get a connection refused.

![mailcatcher_conn_refused](https://cloud.githubusercontent.com/assets/1782799/11915036/ff8d0ece-a662-11e5-9b35-b0dbd66de342.PNG)


When I navigate to http://mailcatcher.pv/, I get a default ubuntu hosting web page.

![default_ubuntu_hosting_image](https://cloud.githubusercontent.com/assets/1782799/11915038/042853c6-a663-11e5-9ee7-872e9b1e0e19.PNG)

I can see that the php.ini was updated properly as seen below.

![mailcatcher_sendmail_path](https://cloud.githubusercontent.com/assets/1782799/11915050/75ea57ca-a663-11e5-8440-77a8370145d1.PNG)

Not sure how to proceed.

Thoughts?

This feels like something that should be provisioned by default.

**Comment by ChrisWiegman** [comment]
Interesting. I haven't come across this as an issue before as it should just be working after a Vagrant Up. Can you please confirm if you're using the Dev branch? I'm wondering if something in the older config has gotten out of whack.

**Comment by crazyjaco** [comment]
I am using the dev branch. Just to be sure, I just did a pull on upstream/dev and did a vagrant up.

I did notice that it was provisioned, though.
![mailcatcher_provisioned](https://cloud.githubusercontent.com/assets/1782799/11918686/8c5c17c2-a709-11e5-93ba-2f47266b3403.PNG)

But when I do a quick status on the service:
![mailcatcher_provisioned_not_running](https://cloud.githubusercontent.com/assets/1782799/11918688/961768ac-a709-11e5-9d7f-5606c8231983.PNG)

That seems odd.

**Comment by ChrisWiegman** [comment]
Interesting I don't even show mail catcher as a service accessible like that. After just blowing away and doing a fresh checkout provision it is just working.

**Comment by crazyjaco** [comment]
I feel compelled to mention I am on Windows 7 and my terminal behaves very poorly at times, but I don't see how that would affect it.

**Comment by crazyjaco** [comment]
What is the url you are using to access mailcatcher? Am I using an incorrect one?

**Comment by ChrisWiegman** [comment]
Nope, yours is correct. I bet the Windows thing might be it though. Perhaps it is blocking port 1080?

**Comment by crazyjaco** [comment]
It looks like Mailcatcher is no longer part of this new v3 setup and that MailHog has taken its place. 
As a result of this, I will close this ticket as no longer being relevant.

Thank you for your support!
