### ISSUE TITLE
Update Documentation on database connection

### ISSUE THREAD

**Issue by eduwass** [ChrisWiegman/Primary-Vagrant#61]
Just a simple note, in the README it says:

>  You can access the database via ssh tunnel into the machine using the local.vagrant hostname, the username vagrant, the password vagrant for ssh, and the username root without a password for MySQL.

And I think that you're no longer using hostname **local.vagrant**, but using **pv** instead works for me.

Maybe update the docs to reflect this?

**Comment by ChrisWiegman** [comment]
Good point. Thanks! Updated in dev (https://github.com/ChrisWiegman/Primary-Vagrant/commit/bc0b382015e0307a02c5d071c2a6b1f21891aa4a)
