### ISSUE TITLE
ENHANCEMENT: rewrite for wp-admin

### ISSUE THREAD

**Issue by Shelob9** [ChrisWiegman/Primary-Vagrant#62]
If I go to `http://stable.wordpress.pv/wp-admin` I get a WordPress 404. Seems like an .htaccess rewrite for that to `http://stable.wordpress.pv/wordpress/wp-admin` would be smart.

**Comment by michaelbeil** [comment]
Good catch @Shelob9.

**Comment by ChrisWiegman** [comment]
WordPress should generate that on install. Is that not the case you're experiencing?
