### ISSUE TITLE
filesystem case insensitive

### ISSUE THREAD

**Issue by timo002** [ChrisWiegman/Primary-Vagrant#63]
Hello,

I noticed that the file system on the PV is case insensitive. This is not usual on Linux and it give's me issues with the production environment because that is case sensitive.

How can I set PV case sensitive?
And why is it case insensitive?

**Comment by ChrisWiegman** [comment]
Hello,

The standard, NFS, mounting of Vagrant will inherit the property from the host OS. My suggestion in your case is, assuming your code is in additional mapped folders, to use the RSYNC option (https://www.vagrantup.com/docs/synced-folders/rsync.html) on your own projects (you can also conversion your vagrant file to this if needed in Vagrantfile). This will prevent the host FS from being visible at all and instead files will be synced back and forth.
