### ISSUE TITLE
Styles, scripts and Images doesn't load.

### ISSUE THREAD

**Issue by FiGO-** [ChrisWiegman/Primary-Vagrant#64]
I just did a fresh install and tried to continue working on the theme I'm developing with pretty much the same pv/map settings as before. But for some reason the theme's style.css and scripts doesn't seem to load and the theme screenshot does not show in the admin. So I reinstalled again but instead out of curiosity I installed one of the free themes from the repository through the admin and the same issue seems to happen. I ssh into **wordpress/content/themes/** and the file is present. Then I ssh into **stable.wordpress.pv/htdocs/wordpress/wp-content/themes/** and the themes that are native to the wordpress install are present as I would expect, but they are the only themes that load correctly. Would it make sense for me to map my themes to the latter directory rather than trying to map to **wordpress/content/themes/** ? Am I overlooking something?

**Comment by ChrisWiegman** [comment]
Are you using the Dev branch? If so, yes, you'll want to use wordpress/content/themes.

**Comment by FiGO-** [comment]
Yes, I'm using the dev branch, but when I use wordpress/content/themes/ as you suggest the css, scripts, and images doesn't load but when I use stable.wordpress.pv/htdocs/wordpress/wp-content/themes/ in my mapping file the styles and scripts load correctly but images still don't load.This is all without modifying anything other than adding a mapping file but other than that Its a fresh install based on instructions given from the docs.

**Comment by ChrisWiegman** [comment]
I’ll take a look. As you’ve noticed I’ve been modifying dev a lot. Let me see if I can reproduce.


Chris Wiegman
Tel: (941) 210-8755 <tel:(941)%20210-8755>
https://www.chriswiegman.com  <https://www.chriswiegman.com/>
 <http://www.facebook.com/chris.wiegman>	 <http://www.facebook.com/chris.wiegman>	 <http://www.facebook.com/chris.wiegman>	 <http://www.facebook.com/chris.wiegman>	 <https://github.com/chriswiegman>

**Comment by FiGO-** [comment]
Thanks, I do have the older version working so I'm good to go. I just happen to love the way you have the folder structure laid out on the dev branch. Its so much easier to navigate and articulate.

**Comment by ChrisWiegman** [comment]
Thanks! and thanks for reporting the issue there. I’ll get to the bottom of it as quickly as I can.


Chris Wiegman
Tel: (941) 210-8755 <tel:(941)%20210-8755>
https://www.chriswiegman.com  <https://www.chriswiegman.com/>
 <http://www.facebook.com/chris.wiegman>	 <http://www.facebook.com/chris.wiegman>	 <http://www.facebook.com/chris.wiegman>	 <http://www.facebook.com/chris.wiegman>	 <https://github.com/chriswiegman>

**Comment by ChrisWiegman** [comment]
This should be solved in the latest dev. Please let me know if you see further errors.

**Comment by FiGO-** [comment]
Hello Chris, My apologies for the late response. I can confirm that everything seems to work perfectly now!. However there seems to be a lot more errors and warnings than before. Everything works fine and the errors doesn't seem to affect any thing but I thought maybe you could make use of the errors I'm receiving. There were a lot so I just cherry picked a few from my terminal:

<pre>
==> default: Error: /usr/bin/wp plugin install user-switching returned 255 instead of one of [0]
==> default: Error: /Stage[main]/Main/Wp::Plugin[user-switching]/Wp::Command[plugin install user-switching]/Exec[/var/www/vip.wordpress.pv/wp wp plugin install user-switching]/returns: change from notrun to 0 failed: /usr/bin/wp plugin install user-switching returned 255 instead of one of [0]

==> default: Error: /usr/bin/wp plugin install wordpress-importer returned 255 instead of one of [0]
==> default: Error: /Stage[main]/Main/Wp::Plugin[wordpress-importer]/Wp::Command[plugin install wordpress-importer]/Exec[/var/www/vip.wordpress.pv/wp wp plugin install wordpress-importer]/returns: change from notrun to 0 failed: /usr/bin/wp plugin install wordpress-importer returned 255 instead of one of [0]

==> default: Notice: /Stage[main]/Main/Wp::Plugin[wordpress-importer]/Wp::Command[plugin activate wordpress-importer]/Exec[/var/www/vip.wordpress.pv/wp wp plugin activate wordpress-importer --network]: Dependency Exec[/var/www/vip.wordpress.pv/wp wp plugin install wordpress-importer] has failures: true

==> default: Error: /usr/bin/wp plugin install polldaddy returned 255 instead of one of [0]
==> default: Error: /Stage[main]/Main/Wp::Plugin[polldaddy]/Wp::Command[plugin install polldaddy]/Exec[/var/www/vip.wordpress.pv/wp wp plugin install polldaddy]/returns: change from notrun to 0 failed: /usr/bin/wp plugin install polldaddy returned 255 instead of one of [0]

==> default: Error: /usr/bin/wp plugin install monster-widget returned 255 instead of one of [0]
==> default: Error: /Stage[main]/Main/Wp::Plugin[monster-widget]/Wp::Command[plugin install monster-widget]/Exec[/var/www/vip.wordpress.pv/wp wp plugin install monster-widget]/returns: change from notrun to 0 failed: /usr/bin/wp plugin install monster-widget returned 255 instead of one of [0]
</pre>

I also noticed that in the old setup there were some dev plugins pre-installed but this setup has none.. Is that by design?

**Comment by ChrisWiegman** [comment]
Hmm. I'll definitely be looking into that ASAP. Hoping to get 3.0 out as soon as Ubuntu 16.04 gets stable. In the meantime, watch for changes here as soon as I can.

In this case it looks like wp-cli is failing though. Can you manually run a wp-cli plugin install from within the Vagrant box?

**Comment by FiGO-** [comment]
Yep.. I was able to successfully install plugins via wp-cli with no issues. I'm using windows if that helps.. I will definitely keep an eye out for your changes..

**Comment by ChrisWiegman** [comment]
Looks like this issue as a wp-cli issue which should be fixed in the next release. For now I've also removed all plugin installs via wp-cli from the initial configuration (VIP support has been moved to an add-on). Hopefully the rest will be updated soon. Please see https://github.com/wp-cli/wp-cli/issues/2627 for reference.
