### ISSUE TITLE
Does not sufficiently wish Chris a happy birthday

### ISSUE THREAD

**Issue by Shelob9** [ChrisWiegman/Primary-Vagrant#67]

**Comment by Shelob9** [comment]
Happy birthday @ChrisWiegman

**Comment by ChrisFlannagan** [comment]
Happy Birthday @ChrisWiegman !!

**Comment by mlbanddrb** [comment]
Happy birthday @ChrisWiegman

**Comment by digisavvy** [comment]
Happy birthday shit head. I mean @chriswiegman

**Comment by masonjames** [comment]
Hope you have the most mediocre birthday ever @ChrisWiegman

**Comment by royboy789** [comment]
Happy birthday @ChrisWiegman

**Comment by sstruemph** [comment]
Happy birthday @ChrisWiegman

**Comment by bamadesigner** [comment]
![img_0018](https://cloud.githubusercontent.com/assets/1513046/16243089/7e0cac4a-37aa-11e6-9717-8398526d6bb4.JPG)

**Comment by mathetos** [comment]
Woot! Someone's got A LOT older!! Happy Birthday to old fart @ChrisWiegman

**Comment by michaelbeil** [comment]
🎉 🎈 🍰  to you @ChrisWiegman.

**Comment by Shelob9** [comment]
Closing as no longer Chris's birthday.
