### ISSUE TITLE
renaming host?

### ISSUE THREAD

**Issue by bobbravo2** [ChrisWiegman/Primary-Vagrant#72]
Is there a single location to rename the hostname from pv -> pv.io? Figured the UX may be better for a TLD that Google recognizes (right now, using pv for start-up is a bit hard, as you have to manually tell Chrome this is http://pv/ not google:pv)

**Comment by ChrisWiegman** [comment]
I've avoided using a real TLD for this due to possible confusion with what might be a real site either now or later. I'm open to further ideas here though.

**Comment by bobbravo2** [comment]
Good news about pv.io is that it isn't (yet) a real site: ![pv.io screenshot](http://cl.circletr.ee/0P0m1l2G3S1T/Image%202016-10-22%20at%2011.03.13%20AM.png)

**Comment by ChrisWiegman** [comment]
Yeah, it's the "yet" I'm not excited about. I'll add it as an alias to the original for now

**Comment by ChrisWiegman** [comment]
I've added pv.io as an alias domain in https://github.com/ChrisWiegman/Primary-Vagrant/commit/1c41416b568a4a5fa096a8813b11081fd5e4f702.
