### ISSUE TITLE
Site Creator

### ISSUE THREAD

**Issue by FiGOBLAC** [ChrisWiegman/Primary-Vagrant#77]
Hello Chris, The site creator is an awesome addition and it would save me a lot time since I love working in the terminal but every time I tried to use it I get "bash: php: command not found". I followed the instructions verbatim and I didn't notice any errors during installation.  Any thoughts?

**Comment by ChrisWiegman** [comment]
Thank! I'll look into it. Do you have PHP installed on your host machine? I'm thinking this is probably a failure of instructions.

**Comment by FiGOBLAC** [comment]
Nope, I don't have php installed on the host machine. Does it need to be? If php is being development via virtualbox why would it need to be on the host machine?
