### ISSUE TITLE
phpmyadmin not setting up properly?

### ISSUE THREAD

**Issue by Alex-Keyes** [ChrisWiegman/Primary-Vagrant#80]
Hello All,

I've been trying to use primary-vagrant as a development box for my wordpress sites.  However phpmyadmin fails everysingle time I run vagrant up to start to spin up the box.  Even though this fails, the box it's self is fine and I can go to the URL to see the default apache setup page.  I was running vagrant version 1.8.1 and I was getting an error with SSH.  Now after upgrading to vagrant version 1.8.5 I am having problems with phpmyadmin.  Additionally, I looked at the repo for phpmyadmin and there doesn't seem to be a RELEASE_4_7_0 branch?  Does this matter?  I'm fairly new to using vagrant to do wordpress localhosting so please forgive any stupid questions.  I've included the error message that I get from the vagrant up command below.  If needed, I can definitely provide the full dump of output that the command gives or anything else that you guys might need.  

Thanks!

Error: /Stage[main]/Main/Vcsrepo[/var/www/default-sites/phpmyadmin/phpmyadmin]: Could not evaluate: Execution of '/usr/bin/git rev-parse HEAD' returned 128: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
==> Primary Vagrant: Use '--' to separate paths from revisions, like this:
==> Primary Vagrant: 'git <command> [<revision>...] -- [<file>...]'
==> Primary Vagrant: HEAD

**Comment by FiGOBLAC** [comment]
I'm having the exact same issue. I tried both the dev branch and the master branch the box seems to be fine but phpmyadmin doesn't show. I'm using windows 10 and a few times I ran as administrator and the error message for phpmyadmin went away but the page still either showed the apache page or didn't show at all. I think I'll try and roll vagrant back a couple versions and see what happens.

**Comment by Alex-Keyes** [comment]
Dope let me know how that goes! Glad I'm not the only person having this problem.

**Comment by Alex-Keyes** [comment]
I reverted my desktop environment to the default Ubuntu settings now after making sure that my virtualbox was a 5.1.18 and the guest extensions were also 5.1.18 and then everything worked!  I'll chalk this error up to my environment not correctly matching with the package.
