### ISSUE TITLE
Vagrantfile not being found?

### ISSUE THREAD

**Issue by crazyjaco** [ChrisWiegman/Primary-Vagrant#81]
Hello,

I am freshly setting up PV and am running into a vagrant issue.
I set up a test site.
From the root of the PV project I ran `vagrant up` and am met with this error:
```
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
```
Running vagrant init informs me that a Vagrantfile already exists.

I'm kind of stuck in the water on this. Most of the googling I've done indicates I'm in the wrong directory, but I don't think I am.

Any help would be greatly appreciated.

**Comment by crazyjaco** [comment]
`sudo vagrant up` fixed the issue.
I guess vagrant doesn't have the right permissions on this machine.

**Comment by ChrisWiegman** [comment]
Might be worth reinstalling Vagrant (assuming you're on a Mac). This isn't a normal problem... at least not that I'm aware of anyway.

**Comment by crazyjaco** [comment]
Yeah, I'm trying to get this setup on a work machine (mac) and its just giving me all sorts of problems I never have at home on my thinkpad.
