### ISSUE TITLE
Unable to load dynamic library '/usr/lib/php/20160303/mysql.so'

### ISSUE THREAD

**Issue by crazyjaco** [ChrisWiegman/Primary-Vagrant#82]
I've finally got everything setup for this now except for one error, which is kinda of important.

`
Primary Vagrant: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/mysql.so' - /usr/lib/php/20160303/mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
`

PHP can't connect to MySQL without this. I've tried reprovisioning a few times to no avail.
Not sure what a good next step would be to troubleshoot this.
That file does not exist on the vagrant box. The closest things I see in that folder are mysqli.so and mysqlnd.so.

**Comment by crazyjaco** [comment]
Just found this:
https://github.com/oerdnj/deb.sury.org/issues/488

I see that phpdismod mysql is in the puppet scripts. I reprovisioned again and noticed this error:

`
==> Primary Vagrant: Notice: /Stage[main]/Main/Exec[wp_code_standards]: Dependency Exec[php_codesniffer] has failures: true
==> Primary Vagrant: Notice: /Stage[main]/Main/Exec[disable_php_mysql]: Dependency Exec[php_codesniffer] has failures: true
==> Primary Vagrant: Error: git clone https://github.com/squizlabs/PHP_CodeSniffer.git /var/phpcs && sudo ln -s /var/phpcs/scripts/phpcs /usr/bin/phpcs && sudo ln -s /var/phpcs/scripts/phpcbf /usr/bin/phpcbf returned 128 instead of one of [0]
==> Primary Vagrant: Error: /Stage[main]/Main/Exec[php_codesniffer]/returns: change from notrun to 0 failed: git clone https://github.com/squizlabs/PHP_CodeSniffer.git /var/phpcs && sudo ln -s /var/phpcs/scripts/phpcs /usr/bin/phpcs && sudo ln -s /var/phpcs/scripts/phpcbf /usr/bin/phpcbf returned 128 instead of one of [0]
==> Primary Vagrant: Warning: /Stage[main]/Main/Exec[wp_code_standards]: Skipping because of failed dependencies
==> Primary Vagrant: Warning: /Stage[main]/Main/Exec[disable_php_mysql]: Skipping because of failed dependencies
`
So it looks like that step is failing for some reason. Investigating...

**Comment by crazyjaco** [comment]
Ok, I moved the disable_php_mysql command above the codesniffer and standards directives and that seemed to get me a little further.

**Comment by crazyjaco** [comment]
Is that change something worthy of a pull request? I can do that if its something worthwhile.

**Comment by ChrisWiegman** [comment]
Sure. This is an interesting fix as the issue has to do with the PHP7.1 package installing an obsolete MySQL extension. It's an upstream issue so, as you've noticed, the solution is to disable the mod manually after it is installed. It can easily go earlier considering the problem you're seeing.

**Comment by crazyjaco** [comment]
Closing issue. Thank you!
