### ISSUE TITLE
Host file is not being updated with pv-hosts URLs

### ISSUE THREAD

**Issue by bsmcgillis** [ChrisWiegman/Primary-Vagrant#85]
Sorry, you can just delete this issue. 

I can't get Primary Vagrant to work at all at this point. And I'm too busy to spend more time trying to get it to work.

**Comment by crazyjaco** [comment]
Did you install the vagrant plugin landrush or vagrant-ghost?

**Comment by bsmcgillis** [comment]
I just followed the instructions on the page for the repo: https://github.com/ChrisWiegman/Primary-Vagrant

So, I did install landrush, but there wasn't any mention of vagrant-ghost.

**Comment by ChrisWiegman** [comment]
@bsmcgillis Can you can me the output from a Vagrant up as well as your pv-hosts file?

**Comment by bsmcgillis** [comment]
Hello, 

I'm sorry, but I've already destroyed my PV box and the project. You can close this issue. I'll try Primary Vagrant again once I'm not so busy. But in the meantime, I've had to revert back to my old development solution.
