### ISSUE TITLE
Files edited in the shared directory are not updating for a website I created

### ISSUE THREAD

**Issue by Alex-Keyes** [ChrisWiegman/Primary-Vagrant#87]
So fortunately I have been able to create project websites now, after that last issue was resolved.  However when I create a site, when I add files to the shared directory in ``/sites/custom.site.here/`` on my host OS, none of the changes happen on the server, I am still seeing the standard Apache2 'IT WORKS!' screen.  Adding both .html and .php files don't change what's served when I visit ``http://custom.site.here.pv``  Is Apache not looking for the directory?  Not quire sure how to resolve this problem.

Thanks!

**Comment by ChrisWiegman** [comment]
Can you share with me the pv-mappings file. Sounds like something is just off in it or the .pp file

**Comment by Alex-Keyes** [comment]
hey Chris,

I actually figured out that this was caused by the mappings being off due to me not specifying a TLD.  After I did that things are working swimmingly.  Maybe explain in the wiki that you need to specify a TLD otherwise the mapping will be incorrect?  It's a dumb error on my part but I would imagine other people are going to do repeat it.  This project is great btw thanks for setting it up!

**Comment by ChrisWiegman** [comment]
Thanks. I will update that (or fix the generator to not worry about it).
