### ISSUE TITLE
Hosts not loaded from user-data/pv-hosts

### ISSUE THREAD

**Issue by redolivedev** [ChrisWiegman/Primary-Vagrant#88]
I'm not sure what I'm doing wrong. I installed ghost and added a file called `pv-hosts` to my `user-data` directory and the hosts never make it to my hosts file. Not a huge deal, but it's kind of annoying to manually add the hosts to my hosts file. Any help would be greatly apprecitated!

[Screenshot of directory structure](https://www.dropbox.com/s/tgsbjiwfz789fj4/Screenshot%202017-05-18%2014.11.19.png?dl=0)

```
==> Primary Vagrant: Checking for host entries
==> Primary Vagrant: adding to (/etc/hosts) : 192.168.13.101    pv      # VAGRANT: 943fc6e8d632afe5f419b9ce796f5b4d (Primary Vagrant) / ba1f55cd-6222-4692-b6be-031d41189546
==> Primary Vagrant: adding to (/etc/hosts) : 192.168.13.101            # VAGRANT: 943fc6e8d632afe5f419b9ce796f5b4d (Primary Vagrant) / ba1f55cd-6222-4692-b6be-031d41189546
==> Primary Vagrant: Setting hostname...
```

Also, here is the output from  `vagrant plugin list`
```
landrush (1.2.0)
vagrant-ghost (0.2.3)
vagrant-share (1.1.8, system)
vagrant-triggers (0.5.3)
vagrant-vbguest (0.14.2)
```

**Comment by ChrisWiegman** [comment]
Try uninstalling landrush if you want to use Ghost. I'm thinking there might be a conflict there.

**Comment by redolivedev** [comment]
Awesome, that worked. Thanks Chris!

**Comment by ChrisWiegman** [comment]
Thank you. I'll make a note of this in the documentation.
