### ISSUE TITLE
 "Failed to parse template"

### ISSUE THREAD

**Issue by FiGOBLAC** [ChrisWiegman/Primary-Vagrant#90]
Hello Chris,  
Any idea why I keep getting this error?
<pre>
 Error: Failed to parse template /vagrant/provision/lib/conf/vhost.conf.erb:
==> Primary Vagrant:   Filepath: /usr/lib/ruby/vendor_ruby/puppet/file_system/file_impl.rb
==> Primary Vagrant:   Line: 75
==> Primary Vagrant:   Detail: No such file or directory @ rb_sysopen - /vagrant/provision/lib/conf/vhost.conf.erb
==> Primary Vagrant:  at /tmp/vagrant-puppet/modules-9638d606c9df1fe8f2636e39044a09f9/apache/manifests/vhost.pp:231 on node pv
==> Primary Vagrant: Error: Failed to parse template /vagrant/provision/lib/conf/vhost.conf.erb:
==> Primary Vagrant:   Filepath: /usr/lib/ruby/vendor_ruby/puppet/file_system/file_impl.rb
==> Primary Vagrant:   Line: 75
==> Primary Vagrant:   Detail: No such file or directory @ rb_sysopen - /vagrant/provision/lib/conf/vhost.conf.erb
==> Primary Vagrant:  at /tmp/vagrant-puppet/modules-9638d606c9df1fe8f2636e39044a09f9/apache/manifests/vhost.pp:231 on node pv
</pre>

**Comment by ChrisWiegman** [comment]
Remove the template line from your .pp file. Since 4.0 it can no longer be used.
