### ISSUE TITLE
command-line line 0: garbage at end of line;

### ISSUE THREAD

**Issue by willisdorden** [ChrisWiegman/Primary-Vagrant#93]
command-line line 0: garbage at end of line; 
i keep getting this error when i try to vagrant ssh into the box. im not sure how to fix this

**Comment by ChrisWiegman** [comment]
This is actually a bug introduced in Vagrant 1.9.8 and affecting all Vagrant boxes (see https://github.com/mitchellh/vagrant/issues/8933). I'm afraid you'll need to downgrade to Vagrant 1.9.7 until it is fixed.

**Comment by willisdorden** [comment]
Thank you for the quick response
