### ISSUE TITLE
Info for using xdebug

### ISSUE THREAD

**Issue by crazyjaco** [ChrisWiegman/Primary-Vagrant#96]
Not an issue, just looking for guidance.

I'm not really sure how to use xdebug in the context of primary vagrant.
Is there something that I can be pointed to for use as reference? or just a brief descriptions of the steps involved?

I'm looking to do some profiliing for a non-performant page and this would be very useful.

I was thinking that I append something to the url, which would cause xdebug to listen, profile and generate the resulting file that webgrind would read and display. Is that far off the mark?

Any help would be apprciated. Thanks!

**Comment by ChrisWiegman** [comment]
Hi!

Most of the docs are for xdebug as a step through tool (using it to see what's going on at a specific point). 

To profile something you have a few options: 

1. turn on profile in your xdebug plugin (see the sceenshot) and use webgrind - http://webgrind.ouro/ - to analayze. The caveat here is many local tools can be hard to use on a complex site and, depending on your OS, you'll very likely have to step up to something beyond it for a large profile. https://kcachegrind.github.io/html/Home.html might be good for that.

2. For ongoing issues or long-term tuning check out New Relic (https://newrelic.com/). What I typically do for performance tuning more than a single issue is run this on the production site as it will give you much more usable data to help you tune properly.

Hope this helps!

**Comment by crazyjaco** [comment]
Thanks for the quick reply! Will dig into these options.

Much appreciated.

**Comment by crazyjaco** [comment]
What screenshot are you referencing?

**Comment by ChrisWiegman** [comment]
![screen shot 2018-04-26 at 13 41 21](https://user-images.githubusercontent.com/394675/39329339-03cd0a62-496c-11e8-9402-27b9efddb994.png)

My apologies. I remembered all but attaching the actual screenshot.

**Comment by crazyjaco** [comment]
Got it working! Thanks so much!
