### ISSUE TITLE
Vagrant 2.1 incompatible with vagrant-triggers

### ISSUE THREAD

**Issue by gefangenimnetz** [ChrisWiegman/Primary-Vagrant#97]
Vagrant 2.1 add support for [triggers](https://www.vagrantup.com/docs/triggers/). Unfortunately that also comes with the issue that the vagrant-triggers plugim is not working well together with the now core feature.

Primary Vagrant currently relies on triggers via the "old" plugin syntax for things like installing default wordpress sites, phpmyadmin and creating database dumps.

Proposal: Switch to the new syntax and drop vagrant-triggers.

**Comment by ChrisWiegman** [comment]
I have no intention of providing further updates for Primary Vagrant. To use it you will need to downgrade Vagrant to 2.0.3 or lower.
